DB_URL = "postgresql://neondb_owner:npg_M1PVNGCLWkp4@ep-rapid-wildflower-a7o4fpj8-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

[email]
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_user = "ryanrylanrahilsingh@gmail.com"
smtp_password = "garfiiskbnlwivob"
from_email = "ryanrylanrahilsingh@gmail.com"
from_name = "Datec-Project-Assistant"

MS_GRAPH_CLIENT_ID = "b2eb38ea-edbd-49d2-97c3-056d29a1bbdc"
MS_GRAPH_CLIENT_SECRET = "953f6da9-f5e2-4757-9f8b-4fae4c8145e7"
MS_GRAPH_TENANT_ID = "5a76df68-d725-47db-a524-73d4ce9272af"
MS_GRAPH_USER_EMAIL = "jayshil.singh@datec.com.fj"