[email]
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_user = "ryanrylanrahilsingh@gmail.com"
smtp_password = "garfiiskbnlwivob"
from_email = "ryanrylanrahilsingh@gmail.com"
from_name = "Datec-Project-Assistant"