DB_URL = "postgresql://neondb_owner:npg_M1PVNGCLWkp4@ep-rapid-wildflower-a7o4fpj8-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

[email]
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_user = "ryanrylanrahilsingh@gmail.com"
smtp_password = "garfiiskbnlwivob"
from_email = "ryanrylanrahilsingh@gmail.com"
from_name = "Datec-Project-Assistant"